### ISSUE TITLE
Some devices do not connect to Odin

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5#16]
In the last months, we have been able to connect:
- Android: Old smartphones connect without problems, but some new ones do not.
- Linux: It depends on the distribution and the driver.
- Windows: It is hard, but in the end some computers do connect.

This should be explored and fixed. It is basic that all kind of devices can connect to Odin.

**Comment by luissequeira** [comment]
See https://github.com/Wi5/odin-wi5/issues/17
