### ISSUE TITLE
Increase the visibility of Odin SSID by sending beacons

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5#17]
The problem is that the beacons have to be sent with the real MAC of the AP, and if the STA answers, then you have to change the MAC by that of the LVAP.

**Comment by luissequeira** [comment]
The visibility of Odin can be increased by increasing the inter-beacon time. We have tested with different values (5/10/100 ms etc.) and now different devices can be connected (Windows, Linux, Android).

**Comment by josemariasaldana** [comment]
Just a minor remark: we are not "increasing the inter-beacon time", but increasing the frequency of beacons. Therefore, we are reducing inter-beacon time in fact. Thanks a lot!

**Comment by juanlucruz** [comment]
TL-WN722N supports values less than 100 ms of beacon interval, during the handoff process. The raspberry wlan adapter supports 500 ms or maybe more. However, the handoff time seems to be proportional to the beacon interval (more or less, three times that value). The minimum time for the TL-WN722N is ~100 ms, and for the raspi adapter ~30 ms.
