### ISSUE TITLE
huge latency 

### ISSUE THREAD

**Issue by hrchhangte** [Wi5/odin-wi5#24]
Hi,
we have the following issue. Could you please help us.
the icmp echo req/reply gives us approx. 4ms on average and the throughput measurement using iperf gives us approx 500kbps!! (download) 5Mbps (upload). 
If you could please suggest where to look for a mis-configuration or issue

Thanks.

**Comment by josemariasaldana** [comment]
Regarding the throughput: the AP created with odin does not include any rate adaptation mechanism. This means that the rate is the one you specify in the .cli file of Click. So the AP will not increase or decrease the rate as a consequence of the status of the channel. You must specify the rate in the .cli script generated with https://github.com/Wi5/odin-wi5-agent/blob/master/agent-click-file-gen.py

**Comment by hrchhangte** [comment]
Thanks for the information. Also, we were having a problem building the .bin file (image) with the modified ath9k driver for tplink wr1043nd, could you please share us the .bin file (image). Thanks in advance.

**Comment by hrchhangte** [comment]
Hi josemariasaldana, the periodic report given by the agents show different rates even though the rate specified in the .cli is 108. Any ideas. Thanks.

**Comment by josemariasaldana** [comment]
https://dl.dropboxusercontent.com/u/67016195/odin-wi5/tplink1043ndv2-openwrt14.07/feb%202016/openwrt-ar71xx-generic-tl-wr1043nd-v2-squashfs-sysupgrade.bin

 

De: hrchhangte [mailto:notifications@github.com] 
Enviado el: lunes, 8 de agosto de 2016 8:16
Para: Wi5/odin-wi5 <odin-wi5@noreply.github.com>
CC: Jose Saldana <jsaldana@unizar.es>; Comment <comment@noreply.github.com>
Asunto: Re: [Wi5/odin-wi5] huge latency (#24)

 

Thanks for the information. Also, we were having a problem building the .bin file (image) with the modified ath9k driver for tplink wr1043nd, could you please share us the .bin file (image). Thanks in advance.

**Comment by hrchhangte** [comment]
Thank you very much. Will try this one.

**Comment by hrchhangte** [comment]
Hi, We still experience a huge frame loss which causes lots of re-transmissions thus reducing the throughput. We tried several things but we still couldn't figure this out. Any suggestions?
Thanks

**Comment by hrchhangte** [comment]
Hi,
Could you please share the latest click (.bin) and click-align file? We have a problem building it.

Thanks in advance.

Regards,
Zela

**Comment by josemariasaldana** [comment]
They are here: https://www.dropbox.com/sh/szwzc3dqarkwl0x/AADAl2Lr4F-7pW_RtxhjmewOa?dl=0

In the folder https://www.dropbox.com/sh/szwzc3dqarkwl0x/AADMzuP3LpQlb2L3EfE1hxiza/Odin-Wi5/click%20compiled%20for%20tp-link%20with%20Odin%20and%20ath9k%20driver/click%20dec%202012?dl=0

**Comment by hrchhangte** [comment]
Hi,
Thanks for the links. 
We are using tplink wr1043nd router and the openwrt version is 14.07 (the image you have given us before), the click (.bin) works for every tplink router?

Regards,
zela

**Comment by josemariasaldana** [comment]
I think Click works with different versions of TP-Link. I mean, provided they use the same architecture. In this case, I think the same binary should work on WR1043nd and other routers.

**Comment by hrchhangte** [comment]
Thanks for the information.
