### ISSUE TITLE
Alignment unknown

### ISSUE THREAD

**Issue by hrchhangte** [Wi5/odin-wi5#25]
Hi,

Got this whenever we run the agent (click_26) even running with the click-al

a_new_7.cli:37: While configuring 'fhcl :: Classifier':
  warning: alignment unknown, but machine is sensitive to alignment
  (Classifier must be told how its input packets are aligned in memory.
  Fix this error either by passing your configuration through click-align,
  or by providing explicit AlignmentInfo. I am assuming the equivalent
  of 'AlignmentInfo(fhcl 4 0)'.)
a_new_7.cli:88: While configuring 'arp_c :: Classifier':
  warning: alignment unknown, but machine is sensitive to alignment
[Odinagent.cc] bssid mask: FF:FF:FF:FF:FF:FF

Thanks.
Zela

**Comment by josemariasaldana** [comment]
No problem. It works anyway.

 

Jose

 

De: hrchhangte [mailto:notifications@github.com] 
Enviado el: miércoles, 10 de agosto de 2016 8:19
Para: Wi5/odin-wi5 <odin-wi5@noreply.github.com>
Asunto: [Wi5/odin-wi5] Alignment unknown (#25)

 

Hi,

Got this whenever we run the agent (click_26) even running with the click-al

a_new_7.cli:37: While configuring 'fhcl :: Classifier':
warning: alignment unknown, but machine is sensitive to alignment
(Classifier must be told how its input packets are aligned in memory.
Fix this error either by passing your configuration through click-align,
or by providing explicit AlignmentInfo. I am assuming the equivalent
of 'AlignmentInfo(fhcl 4 0)'.)
a_new_7.cli:88: While configuring 'arp_c :: Classifier':
warning: alignment unknown, but machine is sensitive to alignment
[Odinagent.cc] bssid mask: FF:FF:FF:FF:FF:FF

Thanks.
Zela

**Comment by hrchhangte** [comment]
Thanks.
