### ISSUE TITLE
ath9k rate control

### ISSUE THREAD

**Issue by gechangwei** [Wi5/odin-wi5#26]
hi：
   i want to know if i do not want use minstrel for rate control, i want use ath9k itself rate control,but in the    file of compat-wireless does not hava the ath9k rate control ,how can i do ?

thankyou

**Comment by josemariasaldana** [comment]
We don't have implemented any rate control algorithm. We use Click Modular Router, and the wireless interfaces are in monitor mode. Therefore, if someone wants to use Minstrel, we should have to add the code.
