### ISSUE TITLE
Odin agents in Virtualbox

### ISSUE THREAD

**Issue by alissonlimasilva** [Wi5/odin-wi5#27]
I'm trying to run the OpenWRT with Click and card ath9k wi-fi in virtualbox. I want to create a Odin environment using virtual machines running OpenWRT, it is possible to make?

**Comment by luissequeira** [comment]
I think it is possible. You can use a usb dongle as a wireless interface.

**Comment by alissonl** [comment]
I'm using the TP-WN722N. My problem is the installation of Click, I am very doubtful, you do not have some link with a tutorial to help me. I am a graduate student, my knowledge is still little

**Comment by josemariasaldana** [comment]
You have information in the wiki: https://github.com/Wi5/odin-wi5/wiki/Cross-compiling-Click-Modular-Router-for-Odin

Best regards

**Comment by alissonl** [comment]
Could you guys help me on how to apply the ath9k patch. I tried everything but I could not.

**Comment by josemariasaldana** [comment]
Please have a look to this page: https://github.com/Wi5/odin-wi5/wiki/Create-OpenWRT-bin-image-including-openvswitch-and-the-ath9k-patch

 

BR

 

De: alissonl [mailto:notifications@github.com] 
Enviado el: sábado, 18 de febrero de 2017 15:06
Para: Wi5/odin-wi5 <odin-wi5@noreply.github.com>
CC: Jose Saldana <jsaldana@unizar.es>; Comment <comment@noreply.github.com>
Asunto: Re: [Wi5/odin-wi5] Odin agents in Virtualbox (#27)

 

Could you guys help me on how to apply the ath9k patch. I tried everything but I could not.

**Comment by alissonl** [comment]
Sorry for the inconvenience again but the ath9k patch seems incomplete. How could I apply?

**Comment by peterrz** [comment]
Copy "debug.c" to the directory and use this commend: $patch < ath9k-bssid-mask.patch
this link has been updated " https://github.com/Wi5/odin-wi5/wiki/Create-OpenWRT-bin-image-including-openvswitch-and-the-ath9k-patch"

**Comment by josemariasaldana** [comment]
Thanks, @peterrz !
