### ISSUE TITLE
22nd April: Make a seamless handover between APs in different channels

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5#3]
Some work has been done so far:

- Adding [code in the agent](https://github.com/Wi5/odin-agent/blob/devel_unizar/src/odinagent.cc): the `case handler_channel_switch_announcement` option.

- Adding [code in the controller](https://github.com/Wi5/odin-controller/blob/devel_unizar/src/main/java/net/floodlightcontroller/odin/master/OdinMaster.java). The functions `handoffClientToAp` and `sendChannelSwitchToClient` are for this aim.

This objective consists of:

- Setting an AP in a channel
- Setting another AP in other channel
- Putting a STA in the middle
- Writing an application in the controller that moves the STA from an AP to the other. This has to integrate the [`handoffClientToAp`](https://github.com/Wi5/odin-controller/blob/devel_unizar/src/main/java/net/floodlightcontroller/odin/master/OdinMaster.java) function with the [`sendChannelSwitchToClient`](https://github.com/Wi5/odin-controller/blob/devel_unizar/src/main/java/net/floodlightcontroller/odin/master/OdinMaster.java) function.
- See what happens: number of lost packets, etc.

Perhaps the hadoffClientToAp function will have to be tuned.

**Comment by luissequeira** [comment]
Almost finished, some tests are required. If someone want to help please contact with us.

https://twitter.com/luissequeirav/status/718078522900758528

**Comment by luissequeira** [comment]
Already done. Please see the branch Handover_Multichannel or contact with us. Closing this issue.
