### ISSUE TITLE
 Help for instaling ath9k driver

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#31]
This link has be deleted{ it was improved by fgg89: https://github.com/fgg89/odin-utilities } please guide me

**Comment by josemariasaldana** [comment]
You have information here: https://github.com/Wi5/odin-wi5/wiki/Create-OpenWRT-bin-image-including-openvswitch-and-the-ath9k-patch, especially in the subsection https://github.com/Wi5/odin-wi5/wiki/Create-OpenWRT-bin-image-including-openvswitch-and-the-ath9k-patch#patch-the-wireless-driver

**Comment by peterrz** [comment]
tnq
