### ISSUE TITLE
Can't ping the gateway

### ISSUE THREAD

**Issue by wucanrui** [Wi5/odin-wi5#32]
Hi. 
I successfully use my laptop connect the odin-agent but  it got not response when I use it to ping the gateway. 
It seem that may the arp is not correct. I specify my laptop MAC address in the odin_client_list file. And change some parameters in agent.click file.

`#### odin_client_list ####
90:b6:86:8d:07:26 192.168.3.11 02:00:00:00:00:00 odin
#####################`

`#### agent.click ########
odinagent::OdinAgent(HWADDR 6C:B0:CE:11:E8:F6, RT rates, CHANNEL 1, DEFAULT_GW 192.168.3.7, DEBUGFS /sys/kernel/debug/ieee80211/phy0/ath9k/bssid_extra, SSIDAGENT odin,DEBUG_ODIN 11, TX_RATE 12, TX_POWER 25, HIDDEN 0)
........
FromHost(ap, HEADROOM 50)                                                                                                                          
  -> fhcl :: Classifier(12/0806 20/0001, -)                                                                                                        
  -> fh_arpr :: ARPResponder(192.168.3.12 e0:94:67:4c:73:18)    //e0:94:67:4c:73:18 is my laptop wireless card MAC                                                                                                       
  -> ToHost(ap)  
..........
odinagent[1]                                                                                                       
  -> decap :: WifiDecap() 
  -> RXStats                                  
  -> arp_c :: Classifier(12/0806 20/0001, -)                                                                       
  -> arp_resp::ARPResponder (192.168.3.7 02:00:00:00:00:00) // ARP fast path for STA                               
  -> [1]odinagent
######################## `

so I just use "ifconfig wlan0 192.168.3.7" in my router. But I can't ping 192.168.3.7 in my laptop.
In the agent, I got a message like "expensive Packet::push; have 10 wanted 14". 

Could anyone tell me what is wrong?  If I want to use a dhcp way, should I disable the DHCP option of "Controll Plane Port" or the "Data Plane Port"?

**Comment by wucanrui** [comment]
An other question is in /etc/config/wireless. Should I set the ssid of wlan0 same as the odin-agent? Could you give me some help.?THX.

**Comment by josemariasaldana** [comment]
The AP SSIDs set in /etc/config/wireless has to be different than the SSID used for Odin/Wi5.
