### ISSUE TITLE
can install odin master and agent in one computer 

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#33]
i want install hole odin project in single pc. it can be done? or I should use external router?

**Comment by josemariasaldana** [comment]
So far we have used different machines. One option is to use virtual machines within a single physical one.

**Comment by peterrz** [comment]
so i want use openwrt router and extra wifi interface( for monitoring) connect them to virtual machines, where the controller installed  and another machin set up  for DHCP, right ? 
another question : why we should use Debian for controller cant be done in ubuntu ?!

**Comment by josemariasaldana** [comment]
It can be done in Ubuntu. We have used Debian, but that is not compulsory.
