### ISSUE TITLE
guide forcollecting device info from agent

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#34]
i want collect all device information(freq,ssid,rate/bit,power ..) form agent and see it in master (like monitoring), please guide me where should i start and what should i do ?

**Comment by josemariasaldana** [comment]
I think you should go to the code of the agent, and add new parameters in https://github.com/Wi5/odin-wi5-agent/blob/Development/src/odinagent.cc

The function `OdinAgent::update_tx_stats(Packet *p)` is the one collecting statistics in the agent.

Then, you should add the corresponding functionalities in the controller. You can have a look to this application https://github.com/Wi5/odin-wi5-controller/blob/Development/src/main/java/net/floodlightcontroller/odin/applications/ShowStatistics.java, which shows the collected statistics.
