### ISSUE TITLE
More info about Statistics.java please

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#35]
this class, which shows the collected statistics (https://github.com/Wi5/odin-wi5-controller/blob/Development/src/main/java/net/floodlightcontroller/odin/applications/ShowStatistics.java)
how actually does it work and how can use it to show?, Any REST API available for this? how can make one ?
thanks to you.

**Comment by josemariasaldana** [comment]
Hi, I have enabled the "Issues" in the Odin Controller repository https://github.com/Wi5/odin-wi5-controller/issues. I think this should go there.
