### ISSUE TITLE
About the agent Time out

### ISSUE THREAD

**Issue by wucanrui** [Wi5/odin-wi5#36]
Hi.
In the receivePing function of AgentManger.java, I saw that there set a timer to check agent by using scheduleAtFixedRate. But there are not the code to update the lastHeard of the agent.
Actually my agent always time out.
Did I ignore some code? Should I add the code to update the lastHeard?
Thanks in advance.

**Comment by josemariasaldana** [comment]
Hi, I have enabled the "Issues" in the Odin Controller repository https://github.com/Wi5/odin-wi5-controller/issues. I think this issue should go there. If you could add some links to the affected files, it would be very helpful.
