### ISSUE TITLE
about click

### ISSUE THREAD

**Issue by xiaojiaozi** [Wi5/odin-wi5#37]
hello:
when I do this 
![image](https://cloud.githubusercontent.com/assets/28896053/26353613/da327a70-3ff3-11e7-9b86-27f9f223400d.png)
I meet this error,
![image](https://cloud.githubusercontent.com/assets/28896053/26353638/f9bfd66c-3ff3-11e7-9504-d396584f1c94.png)
![image](https://cloud.githubusercontent.com/assets/28896053/26353657/036166cc-3ff4-11e7-856e-2f3b8896ed11.png)
and the result is
![image](https://cloud.githubusercontent.com/assets/28896053/26353668/12b90fe4-3ff4-11e7-98c1-f1b5ddf0f355.png)

how can I do about this?
Hope your reply！

**Comment by josemariasaldana** [comment]
Hi, I assume you are cross-compiling Click, i.e. compiling it for OpenWrt. In that case, you have to set all the environment variables properly. You have an example here: https://github.com/Wi5/odin-wi5/wiki/Cross-compiling-Click-Modular-Router-for-Odin

However, this is a Click (https://github.com/kohler/click/) problem, more than a Wi-5 problem.

**Comment by xiaojiaozi** [comment]
Thank you for your reply!
And I have some problems yet：


When I cross compilie I do
![image](https://cloud.githubusercontent.com/assets/28896053/26383337/c7f036d8-4064-11e7-8774-99f228e68428.png)
![image](https://cloud.githubusercontent.com/assets/28896053/26383340/ccd94dec-4064-11e7-891f-cd44d0216f1f.png)
![image](https://cloud.githubusercontent.com/assets/28896053/26383343/d16ae154-4064-11e7-9eac-46e3c9e31108.png)

the result is
![image](https://cloud.githubusercontent.com/assets/28896053/26383346/d4415994-4064-11e7-88b0-81650468518f.png)
Then I do this：

![image](https://cloud.githubusercontent.com/assets/28896053/26383455/5852434c-4065-11e7-8aec-30dc76997379.png)

The elements.conf contains:



![image](https://cloud.githubusercontent.com/assets/28896053/26383465/68c0fee4-4065-11e7-9496-5f41d613c7fa.png)

but when I do this:
![image](https://cloud.githubusercontent.com/assets/28896053/26383468/779e7950-4065-11e7-9d8e-2936dbae1a51.png)
 the result is:
![image](https://cloud.githubusercontent.com/assets/28896053/26383479/8783c8ca-4065-11e7-9671-ff3840bd7d86.png)
![image](https://cloud.githubusercontent.com/assets/28896053/26383485/9587def2-4065-11e7-8eda-7ad2d25e1a2e.png)

How can I do about this error?
Hope your reply!

**Comment by josemariasaldana** [comment]
You have the binary file here: https://github.com/Wi5/odin-wi5-agent/tree/integrate_detection/click_binary_file
