### ISSUE TITLE
about start scripts

### ISSUE THREAD

**Issue by xiaojiaozi** [Wi5/odin-wi5#38]
Hello:
when I run the start scripts ,I met some problems:
![image](https://cloud.githubusercontent.com/assets/28896053/26406015/98d85bb8-40c9-11e7-9bd8-50d12cc6dd08.png)
How can I do about these error?

**Comment by josemariasaldana** [comment]
The question is that we have added a secondary input to the Odin agent for managing the traffic of the secondary interface (for scanning). If you use the latest versions of odin agent and the .cli file, the problem should disappear. Use the last releases: 

https://github.com/Wi5/odin-wi5-agent/releases/tag/v06
https://github.com/Wi5/odin-wi5-controller/releases/tag/v06
