### ISSUE TITLE
Make an AP scan for a STA in other channel

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5#4]
This assumes that [Objective #1: Make a seamless handover between APs in different channels](https://github.com/Wi5/odin/issues/3) is working.

The idea is to make the controller able to make the AP scan in other channel, in order to see if a STA is in the nearby.

**Comment by luissequeira** [comment]
We include more drivers for openwrt in order to use a second USB-wireless card for scanning. See ClientScanning branch. Still testing.

**Comment by luissequeira** [comment]
This is done in MobilityManager branch see: https://github.com/Wi5/odin-wi5-controller/tree/MobilityManager and https://github.com/Wi5/odin-wi5-agent/tree/MobilityManager.
