### ISSUE TITLE
How to  create a mon0 and a mon1 in wireless router

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#41]
this page unavailable
 https://github.com/Wi5/odin-wi5/wiki/Create-the-monitor-interfaces
I need some help  for this task, thanks

**Comment by josemariasaldana** [comment]
Hi,

That part is included in the [start.sh](https://github.com/Wi5/odin-wi5-agent/blob/Development/scripts_start_ap_odin/start.sh) script:

ifconfig wlan0 down
ifconfig wlan1 down
iw phy phy0 interface add mon0 type monitor
iw phy phy1 interface add mon1 type monitor
ifconfig mon0 up
ifconfig mon1 up
ifconfig mon0 mtu 1532
ifconfig mon1 mtu 1532
ifconfig wlan0 up
ifconfig wlan1 up
