### ISSUE TITLE
This wiki about preparing openvswitch didn't work for me 

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#42]
When i Try :swconfig dev switch0 load /etc/config/network
My device didnt work anymore then i should reset it.
I Try to edite firewall first but nothing change, Should i do anything more?

**Comment by josemariasaldana** [comment]
Hi,

I assume you are talking about https://github.com/Wi5/odin-wi5/wiki/Configure-the-network-of-the-AP-after-flashing.-Prepare-OpenVswitch.

The command `$swconfig dev switch0 load /etc/config/network` is for telling `swconfig` to read a configuration from a file. It is useful for checking if your `/etc/config/network` is ok. However, as soon as you use it, your router will have the new network configuration.

I would first modify the three files (`network`, `firewall`, `wireless`) and then restart the router, which will boot with the new configuration.

**Comment by peterrz** [comment]
Hi,
The easiest way is config switch with luci.
