### ISSUE TITLE
some question about Copy the files to the router  After cross-compiling click 

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5#43]
Hi, at end of this wiki you said "
Copy the files to the router
After cross-compiling click and click-align binaries, they have to be copied to the Wi-Fi routers"
but you don't mention where to copy it any specific path ? this binary click we build size it to big 4Mb & 30 Mb i t didn't fit in router (my router is WR1043nd i have only one usb interface. )
 what should we do ?
 { 
      i Check start.sh :
       "## Mount USB
        echo "Mounting USB"
        if [ ! -d "/mnt/usb" ]; then
         mkdir -p /mnt/usb
        fi
        mount /dev/sda1 /mnt/usb/"
what is /dev/sda1 ?
  }
and also i have you previous file ( click_binary_file) contain {click-align_for_AR71xx , click_for_AR71xx}
" it doesn't available anymore", 
can we use it or we should build own click cause every time i got error to build.

**Comment by josemariasaldana** [comment]
We have moved to APs with more than a single USB port. One USB port is used for a memory stick with Click, and the other one for an auxiliary wireless card.

Three possibilities come to mind (none of them has been tested):

- Using a USB hub
- Using this script, which produces a .bin that can be flashed, and includes the Click file: https://github.com/Wi5/odin-wi5/tree/master/Odin_Wi5_firmware_build
- Creating a dummy interface (https://github.com/Wi5/odin-wi5/wiki/If-you-don't-have-a-secondary-wireless-interface)

**Comment by peterrz** [comment]
Hi
So why name tp-link Wr1043ND listed in supported hardware? When this project need 2 usb??!
And Also
I have same error you talk about in kohler/click
"Problem when cross-compiling: error.cc #25"
Any solution? 
Thanks

**Comment by josemariasaldana** [comment]
I have corrected the wiki https://github.com/Wi5/odin-wi5/wiki/Supported-hardware

**Comment by peterrz** [comment]
I will use usb hub and i feed back if it work

**Comment by tomahawk291** [comment]
Dear peterrz,
I have same hardware devices as you (TPLink 1043ND) Have you done your prototype? Can I ask you something about your systems?

**Comment by peterrz** [comment]
@tomahawk291  hi, of course i will be glad to help you

**Comment by tomahawk291** [comment]
@peterrz Thank you!  I am done with part compile for Click but how can we use them, I can not install it in OpenWRT. The author wrote "Start Click" and I don't know what to do with it. I am using TPLink 1043ND v3, are you done with this version?

**Comment by peterrz** [comment]
@tomahawk291  yeah, I have TPLink 1043ND v3 too, after complied click put files (click , click-aligen & agent.cli ) in flash memory, use [ agent-click-file-gen.py ](https://github.com/peterrz/odin-wi5-agent) to build agent.cli , then use flash memory on your router and start running this script [start.sh](https://github.com/peterrz/odin-wi5-agent/tree/master/scripts_start_ap_odin)

**Comment by tomahawk291** [comment]
Thanks! But now I am struggling with USB drive to copy Click. Did you install some special packet? Or may I have your firmware flash file? I really appreciate this since I lost many time for building firmware.

**Comment by peterrz** [comment]
@tomahawk291 did you format your usb drive to ex3/ex4 ?
here is the link [my firmware](https://github.com/peterrz/odin-wi5/tree/master/files%20to%20flash%20in%20the%20routers/Tl-WR1043ND)

**Comment by tomahawk291** [comment]
Yeah, I already format and when I saw log it also recognized my usb but I still can not mount. About your firmware, could you provide your /config/network file in our repository?

**Comment by peterrz** [comment]
then use luci to mount your usb, and also you can use luci too for config network [my config](https://github.com/peterrz/odin-wi5/blob/master/files%20to%20flash%20in%20the%20routers/Tl-WR1043ND/etc.config%20vi%20network%20.txt)

**Comment by tomahawk291** [comment]
I have just flashed your firmware. I saw your network config, you connect openwrt via address 192.168.1.30 and wan port, right?

**Comment by peterrz** [comment]
make sure you install necessary packages and use this command to find your usb drive : 
$block detect > /etc/config/fstab  
$vi /etc/config/fstab   
config 'global'
        option  anon_swap       '0'
        option  anon_mount      '0'
        option  auto_swap       '1'
        option  auto_mount      '1'
        option  delay_root      '5'
        option  check_fs        '0'

config 'mount'
        option  target  '/mnt/sdb1'
        option  uuid    '3E86-1C9C'
        option  enabled '0'



config 'global'
        option  anon_swap       '0'
        option  anon_mount      '0'
        option  auto_swap       '1'
        option  auto_mount      '1'
        option  delay_root      '5'
        option  check_fs        '0'

config 'mount'
        option  target  '/mnt/sda'
        option  uuid    'D0C8-3C42'
        option  enabled '1'

**Comment by peterrz** [comment]
@tomahawk291 my controller is 1.30 , my lan1 is 1.32 and my wan is 1.31, my scenario was little difference
my lan4 was dhcp for install packages via internet

**Comment by tomahawk291** [comment]
I am sorry but I do not find the way to connect to luci web or ssh to openwrt. I have computer with ip 192.168.1.101 and which port and address I can connect to LUCI?

**Comment by peterrz** [comment]
Sorry i forget to say luci isn't intalled Use opkg update and opkg install
luci first, then use ip router to connect it : ip/cgi-bin/luci/

**Comment by tomahawk291** [comment]
Yeah I know, but I can not ssh to router. Could you tell me the **router Ip** and **port**? If i bother you too much, please understand cause I try many time.

**Comment by peterrz** [comment]
No problem i been in your situation i completely understand, i didnt set
any ip on my firmware if you mean that. First time you need telne to set
passwd in 192.168.1.1 after that use putty 192.168.1.1 and port is 22, this
depends what did you do when flash new frameware (sysupgrade.bin). Do you
remove all setting or continue as your old configuration. Please check your
previous ip too.

**Comment by tomahawk291** [comment]
@peterrz I am done with configuration of router and run start script but has one problem:
I follow all steps of start script but when go to this "ifconfig ap up" ?? error no such device.
can I see your "ovs-vsctl show"

**Comment by peterrz** [comment]
ovs-vsctl show
fa425e64-19fe-4465-862b-a6ff899e62ee
    Bridge "br0"
        Controller "tcp:192.168.1.30:6633"
        Port ap
            Interface ap
        Port "br0"
            Interface "br0"
                type: internal
        Port "eth1.4"
            Interface "eth1.4"

first run: ./click < click-align agent.cli & (do you see any change when you run this command ?)
then : ifconfig ap up           
ovs-vsctl add-port br0 ap

**Comment by tomahawk291** [comment]
Thanks! It seems almost the same with my setup 

> first run: ./click < click-align agent.cli & (do you see any change when you run this command ?)

I saw nothing happen with this command, even logread. I am not sure about my agent.cli file. Could you upload your agent.cli for comparison?
And one more, there is no UI for odin controller, right? How you can see the clients and other information?

**Comment by peterrz** [comment]
yeah there is no UI, in logread, follow this link it explain well [link](https://github.com/peterrz/odin-wi5-agent)
here is my agent.cli 
[agent.cli.txt](https://github.com/Wi5/odin-wi5/files/1287289/agent.cli.txt)

**Comment by tomahawk291** [comment]
Thanks! Now when I run the agent.cli there is one error: OdinAgent: Input 2 unused. Output 4 unused. I try, may be my wireless network config is wrong. 
So can I see your **ifconfig -a** and  **etc/config/wireless** ?

**Comment by peterrz** [comment]
before you run it, use ifconfig to see your wlan name in my router i use radio 2 and radio 3 , 
my etc/config/wireless:

config wifi-device  radio0
        option type     mac80211
        option channel  36
        option hwmode   11a
        option path     'virtual/mac80211_hwsim/hwsim0'
        option htmode   VHT80
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio0
        option network  lan
        option mode     ap
        option ssid     wrt
        option encryption none

config wifi-device  radio1
        option type     mac80211
        option channel  36
        option hwmode   11a
        option path     'virtual/mac80211_hwsim/hwsim1'
        option htmode   VHT80
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio1
        option network  lan
        option mode     ap
        option ssid     wrt
        option encryption none

config wifi-device  radio2
        option type     mac80211
        option channel  11
        option hwmode   11g
        option path     'platform/qca955x_wmac'
        option htmode   HT20
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio2
        option network  lan
        option mode     ap
        option ssid    wrt
        option encryption none

config wifi-device  radio3
        option type     mac80211
        option channel  11
        option hwmode   11g
        option path     'platform/ehci-platform.0/usb1/1-1/1-1.2/1-1.2:1.0'
        option htmode   HT20
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio3
        option network  lan
        option mode     ap
        option ssid     openwrt
        option encryption none

**Comment by tomahawk291** [comment]
> option path 'platform/ehci-platform.0/usb1/1-1/1-1.2/1-1.2:1.0'
Does it mean that I have to have another usb wifi card extend? I see you using 2 channel in agent.cli, may I have your "ifconfig -a" information.
Thanks!

**Comment by peterrz** [comment]
Welcome, you should use external wireless( i use usb hub) ,yeah 2 channels
, i dont access to ifconfig right now,

**Comment by tomahawk291** [comment]
Yeah, thank for your help, i still need your ifconfig information. Hope you can provide me soon, I will try more.

**Comment by peterrz** [comment]
@tomahawk291 here is the ifconfig -a
[ifconfig -a.txt](https://github.com/Wi5/odin-wi5/files/1288301/ifconfig.-a.txt)
good luck!

**Comment by tomahawk291** [comment]
Hi @peterrz it is me again, 
Did you succeed in building Click or you click this author provide from this https://github.com/Wi5/odin-wi5-agent/tree/master/click_binary_file ?
If you can upload your Click, I really appreciate your help.

**Comment by peterrz** [comment]
hi @tomahawk291 
this is my  [Click files](https://github.com/peterrz/odin-wi5-agent/tree/master/Click)

**Comment by tomahawk291** [comment]
Dear, when I run click, my screen showed that
![screenshot from 2017-09-11 11-55-29 1](https://user-images.githubusercontent.com/11684530/30323254-6ffa27c8-97f7-11e7-946d-8536bf876f8c.png)

Did you have the same result? I guess there should be one associated AP, but I am not sure what I missed.

**Comment by peterrz** [comment]
yeah i have same results, check the issues #46

**Comment by tomahawk291** [comment]
Thank you @peterrz for supporting me a lot. I saw your issue but after running I saw no ssid from my current access point. Did you enable any ssid (wlan0, wlan1, wlan2) or even ssid name from agent.py file?

**Comment by peterrz** [comment]
your welcome dear @tomahawk291, in OpenWrt wifis are disabled (default), so you should first enable your wifi use command line or Luci
 `wifi`
`uci set wireless.@wifi-device[0].disabled=0`
 `uci commit wireless`

and also did you check [Sanity-check](https://github.com/Wi5/odin-wi5/wiki/Sanity-check)

**Comment by tomahawk291** [comment]
Hi @peterrz are you successful in compiling Click? What is your environment? I need change some codes in click . btw I saw we have some similar work, could I have your contact for discussion? Thanks!

**Comment by peterrz** [comment]
hi @tomahawk291 i use same environment describe in wiki. i update my profile, contact me directly .

**Comment by peterrz** [comment]
@tomahawk291 did you solve your problem?!.
 I'm waiting for your mail.
