### ISSUE TITLE
ttyS0 disabled

### ISSUE THREAD

**Issue by chaitanya4b3** [Wi5/odin-wi5#47]
I have followed all the instructions given in the website. 
It has created, the following files in my bin/ar71xxx directory:
[https://imagebin.ca/v/3dBN8x6jLFvm](url)

- openwrt-ar71xx-generic-uImage-gzip.bin
-openwrt-ar71xx-generic-uImage-lzma.bin
- openwrt-ar71xx-generic-vmlinux.bin

Then I use this file  openwrt-ar71xx-generic-uImage-gzip.bin, and boot the openwrt using auth mode at time of booting:
auth>
The tftp boot is successful and after resetting the board it gives the following error as in link:
https://imagebin.ca/v/3dBNzPAe7JgZ

Help would be appreciated!!!!

**Comment by peterrz** [comment]
dear chaitanya4b3,
for which device you build packages?

**Comment by chaitanya4b3** [comment]
It's our Custom build hardware, with QCA9558AT4A, processor, which I have build using AR71xxx in make menuconfig

**Comment by peterrz** [comment]
are sure your packets size isn't too big? cause this wiki was old and packages size change in the update, lead you to fall to build packages, I recommend you check it in compiling and also can you show me your following files in your bin/ar71xxx directory:
https://imagebin.ca/v/3dBN8x6jLFvm
cause link didn't work anymore.

**Comment by chaitanya4b3** [comment]
They have successfully compiled and have created the bin files:
[https://imagebin.ca/v/3dHJRKbO2l05](url)
[https://imagebin.ca/v/3dHKM9fd3Q93](url)

**Comment by peterrz** [comment]
did you choose `Target Profile` ?

**Comment by chaitanya4b3** [comment]
I chose Target Profile, and in that I chose default profile for all drivers

**Comment by peterrz** [comment]
i don't think openwrt-ar71xx-generic-uImage-gzip.bin suitable to your hardware check the supported list 
https://wiki.openwrt.org/toh/start
and also ask question in this forum
https://forum.openwrt.org/
