### ISSUE TITLE
Middleware for Odin applications: Change channel of the AP from an application running in the controller.

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5#5]
Create a middleware able to change the channel of an AP from an application running in the Controller.

The objective is to be able to change the channel of an AP from the controller. The code is almost ready, but it does not work yet.

These are the functions added in the controller:
- [`setChannelToAgent`](https://github.com/Wi5/odin-controller/blob/devel_unizar/src/main/java/net/floodlightcontroller/odin/master/OdinMaster.java)
- [`getChannelFromAgent`](https://github.com/Wi5/odin-controller/blob/devel_unizar/src/main/java/net/floodlightcontroller/odin/master/OdinMaster.java)

And these are the options added in the agent CC code:
- [`handler_channel`](https://github.com/Wi5/odin-agent/blob/devel_unizar/src/odinagent.cc): it should change the channel of the AP.

**Comment by luissequeira** [comment]
Almost ready. Waiting finals tests.

**Comment by luissequeira** [comment]
This is done in MobilityManager branch see: https://github.com/Wi5/odin-wi5-controller/tree/MobilityManager and https://github.com/Wi5/odin-wi5-agent/tree/MobilityManager.
