### ISSUE TITLE
Chatter and control socket Agent

### ISSUE THREAD

**Issue by uhlik1889** [Wi5/odin-wi5#52]
I am having trouble connecting more than one agent on the same computer, it says chatter socket already bind, but if I change it to unused port, Odin master at the connection with the agent just crashed.

These are the crucial lines in the agent:
control :: ControlSocket("TCP", 6777);
chatter :: ChatterSocket("TCP", 6778);

Any ideas? I need to change both of them, because both are unique to agent, at least it seems.

Regards,
Matej.

**Comment by josemariasaldana** [comment]
You can perhaps add an extra IP address to the ethernet interface https://www.garron.me/en/linux/add-secondary-ip-linux.html

**Comment by uhlik1889** [comment]
I don't need extra IP address, I need a way to connect more than one agent to the controller, but the agents needs to be situated on one PC. I have plenty of IP addresses 127.0.0.0/8

Problem are those sockets.
