### ISSUE TITLE
Send a TPC Request Element from the AP to the STA

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5#7]
**Note**: This assumes [Objective #4](https://github.com/Wi5/odin/issues/6) has been achieved. Otherwise this information makes no sense, as it would be useless. If the power cannot be changed, then why should we get its value?

The idea is that the Controller should be able to know the power and the link margin of a STA.

This implies that the AP has to build a _TPC Request Element_ (see 802.11-2012, Section 8.4.2.18).

Then we should see if the STAs answer or not.

**Comment by haizeiwang507** [comment]
@ josemariasaldana
     Hello,I plan to achieve the function about: enable per-packet TPC on AR9002 based chips.but my openwrt version is lower (git clone git://git.openwrt.org/14.07/openwrt.git), there is no TPC function in ath9k(compat-wireless-2014-05-22) ,  Can you tell me your openwrt'version?   I can't install openvswitch before when openwrt'version is higher. thank you!

**Comment by josemariasaldana** [comment]
Hi,

 

If you could help us enabling per-packet TPC, it would be great.

 

We have been working with OpenWrt 14.07 so far. But I think there would be no problem on moving to another version if it is necessary to make per-packet TPC run. Do recent versions support it?

 

As you say, it seems there is some issue with openvswitch in that case. We could try to fix it in that case.

 

BR,

 

Jose

 

De: haizeiwang507 [mailto:notifications@github.com] 
Enviado el: miércoles, 6 de abril de 2016 10:10
Para: Wi5/odin-wi5 <odin-wi5@noreply.github.com>
CC: Jose Saldana <jsaldana@unizar.es>
Asunto: Re: [Wi5/odin-wi5] Objective #5: Send a TPC Request Element from the AP to the STA (#7)

 

@ josemariasaldana
Hello,I plan to achieve the function about: enable per-packet TPC on AR9002 based chips.but my openwrt version is lower (git clone git://git.openwrt.org/14.07/openwrt.git), there is no TPC function in ath9k(compat-wireless-2014-05-22) , Can you tell me your openwrt'version? I can't install openvswitch before when openwrt'version is higher. thank you!

**Comment by haizeiwang507** [comment]
HI,
First it must have TPC function If we want to enable per-packet TPC,  the TPC is added after backports-4.0.1-1.tar (we can found in 'static ssize_t write_file_tpc write_file_tpc'  of backports-4.0.1-1/drivers/net/wireless/ath/ath9k/debug.c)  ,so the first problem is how to use backports-4.0.1-1 in odin.

**Comment by josemariasaldana** [comment]
Well, the first objective would be to have an openwrt version with backports-4.0.1-1 driver. After that, applying the patch would be straightforward (you only have to add two [blocks of code](https://github.com/Wi5/odin-wi5/blob/master/odin-patch-driver-ath9k/ath9k-bssid-mask.patch)). So we could use that in Odin.

Are you planning to try this?

**Comment by haizeiwang507** [comment]
yes. but it's not easy to have an openwrt version with backports-4.0.1-1 driver.

**Comment by haizeiwang507** [comment]
@ josemariasaldana
Hi, i have put the patch of TPC  to the odin systerm and changed tcp_enable=ture (Default is flase in ath9k/hw.c), but i can't run tpc  function(with comand : set phy phy0 set txpower limit [10]).my network card is ar9280.  and i have find some explain  in ieee802.11h about tpc. it had used in 802.11n 5G in  Europe ,it seem to say that tpc is use from STA to STA . now , i plan to use tpc in AP mode ，but  the information about tpc operating mechanism is too less that i have not found ever  , (maybe tpc mechanism is used in your country ,can you help me?such as packets catched by tcpdump when tpc running or some informations ), Thanks

**Comment by josemariasaldana** [comment]
It seems that per-packet TPC is not possible. Although Click writes it in the Radiotap, the Linux kernel just ignores it.
